### PR TITLE
refrain from using package (reserved word)

### PR DESCRIPTION
**Pull request by mightyiam**

### CODE REVIEW

**Comment by mightyiam** [comment]
https://stackoverflow.com/a/12114140/359072

**Comment by mightyiam** [comment]
Another idea: `pkg` or `object`.

**Comment by jmanero** [comment]
In ECMA, reserved words only apply to identifiers (e.g. function/variable names), not identifier names: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Reserved_word_usage

However, [you are technically correct](http://www.quickmeme.com/img/62/62f538b129e13afc6c7d9b9278b63f63f4c91e1f8fd1077c36e088039bf538f8.jpg) in the scope of Node.JS, where the identifier name is being exported into the root of the module's namespace and has the potential to conflict with some future addition to the `require`/`module` interface. I'm going to close this in favor of exporting the object as `content`

**Comment by mightyiam** [comment]
Sure. Also see https://github.com/jmanero/auto-package/issues/9#issuecomment-76181465.

**Pull request closed without merging**
